name: mesh_funcspace
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cython
  - imageio
  - numpy=1.15.4
  - numpy-base=1.15.4
  - matplotlib
  - matplotlib-base
  - pandas
  - pillow
  - pyembree
  - pytest
  - python=3.7
  - pytorch::pytorch=1.1.0
  - pytorch::torchvision
  - cudatoolkit=9.0
  - tensorboardx
  - pyyaml
  - scikit-image
  - scipy
  - tqdm
  - trimesh
  - pip
  - pip:
    - h5py
    - plyfile

