name: mesh_funcspace
channels:
  - conda-forge
  - pytorch
  - intel
  - defaults
dependencies:
  - cython
  - imageio
  - numpy
  - numpy-base
  - matplotlib
  - matplotlib-base
  - pandas
  - pillow
  - pyembree
  - pytest
  - python=3.7
  - pytorch::pytorch=1.6.0
  - pytorch::torchvision
  - cudatoolkit=
  - tensorflow
  - tensorboard
  - pyyaml
  - scikit-image
  - scipy
  - tqdm
  - trimesh
  - intel::mkl
  - pip
  - pip:
    - h5py
    - plyfile

